### ISSUE TITLE
已pull registry-proxy:v1.2.0 镜像，但pod一直创建失败，提示pull failed

### ISSUE THREAD

**Issue by ndzuki** [ketches/registry-proxy#2]
![图片](https://github.com/ketches/registry-proxy/assets/40823052/8552705f-1e3a-47a7-a1b2-cc80ac1196f9)

![图片](https://github.com/ketches/registry-proxy/assets/40823052/773f0788-bd91-49a2-b396-86c628d6adc2)

OS：WSL2 arch linux
Driver: podman
cluster: minikube

**Comment by poneding** [comment]
> ![图片](https://private-user-images.githubusercontent.com/40823052/335467525-8552705f-1e3a-47a7-a1b2-cc80ac1196f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDU3MTEsIm5iZiI6MTcyMDQwNTQxMSwicGF0aCI6Ii80MDgyMzA1Mi8zMzU0Njc1MjUtODU1MjcwNWYtMWUzYS00N2E3LWExYjItY2M4MGFjMTE5NmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAyMjMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYzZjOTMzY2ZlNmI2YWQwNTRmOTI3MjhiMmUzZjBhMjM0NjljZmE2N2E3ZDhjODlmN2U0ZDRlOTI4YjI1MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-D4x41WrVp3_kfFkon2P4EN30rVfomD60enrZuXjcxs)
> 
> ![图片](https://private-user-images.githubusercontent.com/40823052/335467134-773f0788-bd91-49a2-b396-86c628d6adc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDU3MTEsIm5iZiI6MTcyMDQwNTQxMSwicGF0aCI6Ii80MDgyMzA1Mi8zMzU0NjcxMzQtNzczZjA3ODgtYmQ5MS00OWEyLWIzOTYtODZjNjI4ZDZhZGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAyMjMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNDdmNDRjNTI4OWY3MWJlMTBkOGRmOGY0MTgxNDdjODM4NjYzMmQ4Mzg1YTUyZDhhZTg0M2QyYzdlNWYwZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p7UNMQ6pgUln-z7dDgwXj0GdVrM5OW-6-Pj33IWTYZQ)
> 
> OS：WSL2 arch linux Driver: podman cluster: minikube

我这边无法复现你的问题，你有没有在你的网络环境里尝试使用 docker pull 呢？
