### ISSUE TITLE
拉取镜像失败，提示failed to fetch anonymous token错误

### ISSUE THREAD

**Issue by kunlun122** [ketches/registry-proxy#3]
使用containerd拉取镜像失败
ctr image pull docker.ketches.cn/library/nginx:latest docker.ketches.cn/library/nginx:latest: resolving      |--------------------------------------|  elapsed: 31.4s                          total:   0.0 B (0.0 B/s)                                          INFO[0031] trying next host                              error="failed to authorize: failed to fetch anonymous token: Get \"https://auth.docker.io/token?scope=repository%3Alibrary%2Fnginx%3Apull&service=registry.docker.io\": dial tcp 199.59.148.222:443: i/o timeout" host=docker.ketches.cn ctr: failed to resolve reference "docker.ketches.cn/library/nginx:latest": failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fnginx%3Apull&service=registry.docker.io": dial tcp 199.59.148.222:443: i/o timeout
详细报错如下：
![image](https://github.com/user-attachments/assets/0afd5f8a-e669-4dbe-bb3d-b32fd7dc7f79)

获取v2接口，提示401错误，然后跳转到auth.docker.io获取token。我试过阿里云的镜像，获取v2一样报401，但是跳转到[https://dockerauth.cn-hangzhou.aliyuncs.com/auth获取token。](https://dockerauth.cn-hangzhou.aliyuncs.com/auth%E8%8E%B7%E5%8F%96token%E3%80%82)

**Comment by awslshadowstar** [comment]
> 使用containerd拉取镜像失败 ctr image pull docker.ketches.cn/library/nginx:latest docker.ketches.cn/library/nginx:latest: resolving |--------------------------------------| elapsed: 31.4s total: 0.0 B (0.0 B/s) INFO[0031] trying next host error="failed to authorize: failed to fetch anonymous token: Get "[https://auth.docker.io/token?scope=repository%3Alibrary%2Fnginx%3Apull&service=registry.docker.io\](https://auth.docker.io/token?scope=repository%3Alibrary%2Fnginx%3Apull&service=registry.docker.io%5C)": dial tcp 199.59.148.222:443: i/o timeout" host=docker.ketches.cn ctr: failed to resolve reference "docker.ketches.cn/library/nginx:latest": failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fnginx%3Apull&service=registry.docker.io": dial tcp 199.59.148.222:443: i/o timeout 详细报错如下： ![image](https://private-user-images.githubusercontent.com/16523425/370645869-0afd5f8a-e669-4dbe-bb3d-b32fd7dc7f79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDIyMTksIm5iZiI6MTcyNzYwMTkxOSwicGF0aCI6Ii8xNjUyMzQyNS8zNzA2NDU4NjktMGFmZDVmOGEtZTY2OS00ZGJlLWJiM2QtYjMyZmQ3ZGM3Zjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA5MjUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYmZhMWQ2NzUwMjQ2NWJiZDgxMmRkYzQ5YTVmZjUyMmJlOGU3NDUzMDM3M2UyYzMyYjIzNDQ1NTNmNmEzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.st2XkzIa_QH3rgHiUPSOxlq_ZFR_MOLbkOcx3lua2NU)
> 
> 获取v2接口，提示401错误，然后跳转到auth.docker.io获取token。我试过阿里云的镜像，获取v2一样报401，但是跳转到[https://dockerauth.cn-hangzhou.aliyuncs.com/auth获取token。](https://dockerauth.cn-hangzhou.aliyuncs.com/auth%E8%8E%B7%E5%8F%96token%E3%80%82)

相同的报错
![image](https://github.com/user-attachments/assets/31c223bb-8c5a-44e1-b381-4b5187ed5e23)

**Comment by awslshadowstar** [comment]
> > 使用containerd拉取镜像失败 ctr image pull docker.ketches.cn/library/nginx:latest docker.ketches.cn/library/nginx:latest: resolving |--------------------------------------| elapsed: 31.4s total: 0.0 B (0.0 B/s) INFO[0031] trying next host error="failed to authorize: failed to fetch anonymous token: Get "[https://auth.docker.io/token?scope=repository%3Alibrary%2Fnginx%3Apull&service=registry.docker.io](https://auth.docker.io/token?scope=repository%3Alibrary%2Fnginx%3Apull&service=registry.docker.io%5C)": dial tcp 199.59.148.222:443: i/o timeout" host=docker.ketches.cn ctr: failed to resolve reference "docker.ketches.cn/library/nginx:latest": failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fnginx%3Apull&service=registry.docker.io": dial tcp 199.59.148.222:443: i/o timeout 详细报错如下： ![image](https://private-user-images.githubusercontent.com/16523425/370645869-0afd5f8a-e669-4dbe-bb3d-b32fd7dc7f79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDIyMTksIm5iZiI6MTcyNzYwMTkxOSwicGF0aCI6Ii8xNjUyMzQyNS8zNzA2NDU4NjktMGFmZDVmOGEtZTY2OS00ZGJlLWJiM2QtYjMyZmQ3ZGM3Zjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA5MjUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYmZhMWQ2NzUwMjQ2NWJiZDgxMmRkYzQ5YTVmZjUyMmJlOGU3NDUzMDM3M2UyYzMyYjIzNDQ1NTNmNmEzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.st2XkzIa_QH3rgHiUPSOxlq_ZFR_MOLbkOcx3lua2NU)
> > 获取v2接口，提示401错误，然后跳转到auth.docker.io获取token。我试过阿里云的镜像，获取v2一样报401，但是跳转到[https://dockerauth.cn-hangzhou.aliyuncs.com/auth获取token。](https://dockerauth.cn-hangzhou.aliyuncs.com/auth%E8%8E%B7%E5%8F%96token%E3%80%82)
> 
> 相同的报错 ![image](https://private-user-images.githubusercontent.com/52888924/371842004-31c223bb-8c5a-44e1-b381-4b5187ed5e23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDI0NDQsIm5iZiI6MTcyNzYwMjE0NCwicGF0aCI6Ii81Mjg4ODkyNC8zNzE4NDIwMDQtMzFjMjIzYmItOGM1YS00NGUxLWIzODEtNGI1MTg3ZWQ1ZTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA5MjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YTg0NTQ5Y2IyYmQ3NjYzY2Q5Njc2ZmU2ZDkzMGNkNmFiOThlZTdiYmMxN2M2MzAzMGI1ZDBlZmY0ZDFmY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MR1w8clgtRaPMpqMPh3Z-J3EXEjEw-F866KOGzI2kzU)

但是直接通过dockerpull是可以正常拉取的
![image](https://github.com/user-attachments/assets/b0b40240-e6e6-45a6-87fd-f4527bb1acc1)

**Comment by poneding** [comment]
已修复。
项目：[cloudflare-registry-proxy](https://github.com/ketches/cloudflare-registry-proxy)
提交：[dfe8e1265edc3e60fbb4b34b4071f85f5e7169a1](https://github.com/ketches/cloudflare-registry-proxy/commit/dfe8e1265edc3e60fbb4b34b4071f85f5e7169a1)
