### ISSUE TITLE
增加指定命名空间的镜像代理使用指定镜像源

### ISSUE THREAD

**Issue by nakroy** [ketches/registry-proxy#4]
作者您好，我使用过您的registry-proxy有一段时间了，功能非常棒，完美解决了国内网络无法正常拉取主流国外镜像的问题。

我在使用过程中也产生了这样一种需求：我的部分镜像组件是自行构建的，并定期推送到基于harbor构建的私有镜像仓库，因此我们在拉取这类镜像时（一般是指定的命名空间），会需要专门指定这个镜像源。

如果能在registry-proxy的配置文件中增加：`指定命名空间的镜像代理，使用指定镜像源` 这一功能，就能全局管理所有命名空间下的镜像源设置了，方便集群的管理，希望能增加这一设置。

最后还是非常感谢作者开源的这个项目

**Comment by poneding** [comment]
没有太明白你的意思。为什么自己构建的私有镜像仓库需要用到镜像代理呢？
还是说你的意思是你 Pod 镜像是 `namespace/image-a` 需要自动映射成 `your-horbor.com/namespace/image-a`?

**Comment by nakroy** [comment]
> 没有太明白你的意思。为什么自己构建的私有镜像仓库需要用到镜像代理呢？ 还是说你的意思是你 Pod 镜像是 `namespace/image-a` 需要自动映射成 `your-horbor.com/namespace/image-a`?
可能没有说的太明白，主要是考虑这种情况：
1. 部署的组件使用的是私有镜像仓库中的镜像，而公共镜像仓库没有；

**Comment by nakroy** [comment]
可能没说的太清楚，我重新解释一下：

1. 部署一个命名空间下的多个组件，这些组件使用到的镜像为私有镜像仓库中的镜像，公开镜像仓库没有；

2. 因为私有镜像仓库只存放自制的一些镜像，因此只有在部署这些命名空间下的组件时，需要选择从私有镜像仓库地址拉取镜像，否则常规情况下registry-proxy会自动选择从公开代理源拉取镜像；

3. 在其他常规的部署中，还是会选择使用公开的镜像代理源。

所以在registry-proxy的`ConfigMap`中希望可以增加新的键值对设置，key对应命名空间，value对应镜像源地址，让registry-proxy可以正确拉取这部分镜像

**Comment by poneding** [comment]
> 可能没说的太清楚，我重新解释一下：
> 
> 1. 部署一个命名空间下的多个组件，这些组件使用到的镜像为私有镜像仓库中的镜像，公开镜像仓库没有；
> 2. 因为私有镜像仓库只存放自制的一些镜像，因此只有在部署这些命名空间下的组件时，需要选择从私有镜像仓库地址拉取镜像，否则常规情况下registry-proxy会自动选择从公开代理源拉取镜像；
> 3. 在其他常规的部署中，还是会选择使用公开的镜像代理源。
> 
> 所以在registry-proxy的`ConfigMap`中希望可以增加新的键值对设置，key对应命名空间，value对应镜像源地址，让registry-proxy可以正确拉取这部分镜像

如果你的某个命名空间只用来部署私有镜像仓库中的镜像，并且不想使用镜像代理，那么你就将命名空间配置到 `excludeNamespaces` （排除命名空间）中就可以了。

**Comment by nakroy** [comment]
> > 可能没说的太清楚，我重新解释一下：
> > 
> > 1. 部署一个命名空间下的多个组件，这些组件使用到的镜像为私有镜像仓库中的镜像，公开镜像仓库没有；
> > 2. 因为私有镜像仓库只存放自制的一些镜像，因此只有在部署这些命名空间下的组件时，需要选择从私有镜像仓库地址拉取镜像，否则常规情况下registry-proxy会自动选择从公开代理源拉取镜像；
> > 3. 在其他常规的部署中，还是会选择使用公开的镜像代理源。
> > 
> > 所以在registry-proxy的`ConfigMap`中希望可以增加新的键值对设置，key对应命名空间，value对应镜像源地址，让registry-proxy可以正确拉取这部分镜像
> 
> 如果你的某个命名空间只用来部署私有镜像仓库中的镜像，并且不想使用镜像代理，那么你就将命名空间配置到 `excludeNamespaces` （排除命名空间）中就可以了。

这是之前一直使用的方法。如果使用helm部署倒是不用考虑这个问题，一般有`global.repository`选项
